In [6]:
import pandas as pd
df = pd.read_csv("AI_Human.csv")

In [7]:
df

                                                     text  generated
0       Cars. Cars have been around since they became ...        0.0
1       Transportation is a large necessity in most co...        0.0
2       "America's love affair with it's vehicles seem...        0.0
3       How often do you ride in a car? Do you drive a...        0.0
4       Cars are a wonderful thing. They are perhaps o...        0.0
...                                                   ...        ...
487230  Tie Face on Mars is really just a big misunder...        0.0
487231  The whole purpose of democracy is to create a ...        0.0
487232  I firmly believe that governments worldwide sh...        1.0
487233  I DFN't agree with this decision because a LFT...        0.0
487234  Richard Non, Jimmy Carter, and Bob Dole and ot...        0.0

[487235 rows x 2 columns]

In [21]:
print(df.columns)

Index(['text', 'generated'], dtype='object')

In [25]:
print(df.head())
print(df['generated'].value_counts())

                                                text  generated
0  Cars. Cars have been around since they became ...          0
1  Transportation is a large necessity in most co...          0
2  "America's love affair with it's vehicles seem...          0
3  How often do you ride in a car? Do you drive a...          0
4  Cars are a wonderful thing. They are perhaps o...          0
generated
0    305797
1    181438
Name: count, dtype: int64

In [24]:
df["generated"] = df["generated"].astype(int)

In [27]:
human_only = df[df['generated']==0]

In [28]:
df

                                                     text  generated
0       Cars. Cars have been around since they became ...          0
1       Transportation is a large necessity in most co...          0
2       "America's love affair with it's vehicles seem...          0
3       How often do you ride in a car? Do you drive a...          0
4       Cars are a wonderful thing. They are perhaps o...          0
...                                                   ...        ...
487230  Tie Face on Mars is really just a big misunder...          0
487231  The whole purpose of democracy is to create a ...          0
487232  I firmly believe that governments worldwide sh...          1
487233  I DFN't agree with this decision because a LFT...          0
487234  Richard Non, Jimmy Carter, and Bob Dole and ot...          0

[487235 rows x 2 columns]

In [29]:
human_only

                                                     text  generated
0       Cars. Cars have been around since they became ...          0
1       Transportation is a large necessity in most co...          0
2       "America's love affair with it's vehicles seem...          0
3       How often do you ride in a car? Do you drive a...          0
4       Cars are a wonderful thing. They are perhaps o...          0
...                                                   ...        ...
487229  In "The Challenge of Exploring Venus" the auth...          0
487230  Tie Face on Mars is really just a big misunder...          0
487231  The whole purpose of democracy is to create a ...          0
487233  I DFN't agree with this decision because a LFT...          0
487234  Richard Non, Jimmy Carter, and Bob Dole and ot...          0

[305797 rows x 2 columns]

In [30]:
df = df[df["generated"] == 0]

In [31]:
df

                                                     text  generated
0       Cars. Cars have been around since they became ...          0
1       Transportation is a large necessity in most co...          0
2       "America's love affair with it's vehicles seem...          0
3       How often do you ride in a car? Do you drive a...          0
4       Cars are a wonderful thing. They are perhaps o...          0
...                                                   ...        ...
487229  In "The Challenge of Exploring Venus" the auth...          0
487230  Tie Face on Mars is really just a big misunder...          0
487231  The whole purpose of democracy is to create a ...          0
487233  I DFN't agree with this decision because a LFT...          0
487234  Richard Non, Jimmy Carter, and Bob Dole and ot...          0

[305797 rows x 2 columns]

In [32]:
df.to_csv("human_text_only.csv", index=False)

In [3]:
df["generated"] = df["generated"].astype(int)

In [4]:
AI_only= df[df["generated"]==1]

In [5]:
df.to_csv("ai_text_only.csv",index = False)

In [6]:
import pandas as pd
import numpy as np

In [7]:
human_df = pd.read_csv("human_text_only.csv")
ai_df = pd.read_csv("ai_text_only.csv")

In [8]:
def split_dataframe(df,chunk_size):
    df = df.sample(frac=1,random_state=42).reset_index(drop=True)
    return [df.iloc[i:i+chunk_size]for i in range(0,len(df),chunk_size)]
human_chunks = split_dataframe(human_df,5000)
ai_chunks= split_dataframe(ai_df,5000)

In [9]:
for idx,chunk in enumerate(human_chunks):
    chunk.to_csv(f'human_chunk_{idx+1}.csv',index=False)
for idx,chunk in enumerate(ai_chunks):
    chunk.to_csv(f'ai_chunk_{idx+1}.csv',index=False)