In [9]:
import pandas as pd
import os

In [10]:
df_human = pd.read_csv("../data/Separated_csv_1/non_native_human/long_text_chunks/long_text_chunk_0.csv", nrows = 15000)

df_human.head()

                                                text  generated
0  i 'm NORP and i hope he joins our PERSON are b...          0
1  NORP are n't exactly all sunshine and roses ei...          0
2  this led to some confusion because mummy alway...          0
3  [ the massacres of NORP during EVENT ] ( URL )...          0
4  all his back and forth between `` i will kill ...          0

In [11]:
df_ai = pd.read_csv("../data/Separated_csv_1/responses_csv/responses_processed.csv", nrows = 15000)

df_ai.head()

                                                text  generated
0  I appreciate your query, and as Grok, an AI bu...          1
1  Below is a comprehensive report on the topic o...          1
2  Below is a 1000-word monologue written in the ...          1
3  Below is a comprehensive SEO-optimized article...          1
4  **Prompt:**  \nIn a bustling modern city, towe...          1

In [12]:
combined_df = pd.concat([df_human, df_ai], ignore_index=True)

combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       29979 non-null  str
 1   generated  30000 non-null  int64
dtypes: int64(1), str(1)
memory usage: 468.9 KB

In [13]:
df_cleaned = combined_df.dropna()
df_cleaned.info()

<class 'pandas.DataFrame'>
Index: 29979 entries, 0 to 29999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   text       29979 non-null  str
 1   generated  29979 non-null  int64
dtypes: int64(1), str(1)
memory usage: 702.6 KB

In [16]:
output_path = "../data/mixed_chunk_data/AI_HUMAN_BALANCED.csv"

In [17]:
df_cleaned.to_csv(output_path)